### ISSUE TITLE
calculating pmi dictionary

### ISSUE THREAD

**Issue by PhyloStar** [evolaemp/online_cognacy_ident#5]
@pavelsof I saw that you used CogDetect library for extracting the code. I suggest to not use that library since due to reasons beyond my control the library no longer reflects the right way to train the online PMI model. 

Please use the https://github.com/PhyloStar/OnlinePMI repo which is the right model and code.

I will add your NW code to the OnlinePMI repo and add you to the repo as colloborator.

**Comment by pavelsof** [comment]
Thank you, I will start replacing the code in this repo.

**Comment by pavelsof** [comment]
This should be now fixed with c55d5b6f38866cc6b2c0108ab834748c6e022cb2 and 4b74e7103d097e95563b0b78ddb41bc239ef9599 :)
